version: '2.1'
services:
  InterfaceLayer:
    image: payara/server-full:latest
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - "C:/Users/Administrator/payara/apps/ZooReportSystem/InterfaceLayer:/opt/payara/deployments"
  ServiceLayer:
    image: payara/server-full:latest
    ports:
      - "2020:8080"
      - "2121:4848"
    volumes:
      - "C:/Users/Administrator/payara/apps/ZooReportSystem/ServiceLayer:/opt/payara/deployments"
    environment:
      - "dbDriver=/opt/payara/appserver/glassfish/domains/production/lib/postgresql.jar"
      - "dbUser=postgres"
      - "dbPassword=postgres"
      - "dbUrl=jdbc:DataLayer://postgres/"
  DataLayer:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"